# -*- coding: utf-8 -*-
"""CSE303_Lab08_Linear_Polynomial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sxj9I-gVC1dhbH60TsxIIMW4yWaOklnJ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

df = np.read_csv('yield.csv')
#%%
X = np.arange('Temp')
y = np.array('Yield')
print (X)
print (y)
#%%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/3, random_state = 0)
print(X_train)
print(y_train)
print(X_test)
print(y_test)

regressor = LinearRegression()
regressor.fit(X_train.reshape(-1,1), y_train)

y_pred = regressor.predict(X_test.reshape(-1,1))
print(y_pred)

# y = a+bx
print(regressor.coef_) #b
print(regressor.intercept_) #a

plt.scatter(X_train, y_train, color = 'red')
plt.plot(X_train, regressor.predict(X_train.reshape(-1,1)), color = 'blue')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('For Training Dataset')
plt.show()

plt.scatter(X_test, y_test, color = 'red')
plt.plot(X_test, regressor.predict(X_test.reshape(-1,1)), color = 'blue')
plt.xlabel('X')
plt.ylabel('Y')
plt.title('For Test Dataset')
plt.show()

from sklearn.preprocessing import PolynomialFeatures

polynomial_features = PolynomialFeatures(degree=2)
X_train_poly = polynomial_features.fit_transform(X_train.reshape(-1,1))

print(X_train.reshape(-1,1))
print(X_train_poly)

poly_regressor = LinearRegression()
poly_regressor.fit(X_train_poly, y_train)
print(poly_regressor.coef_)
print(poly_regressor.intercept_)
# y = 2x^2 + x^1 + 1

y_poly_pred = poly_regressor.predict(X_train_poly)
print('Predicted value (Polynomial):', y_poly_pred)
print('Predicted value (Linear):', regressor.predict(X_train.reshape(-1,1)))
print('Actual value:', y_train)

import operator

plt.scatter(X_train, y_train, color = 'red')

# for sorting the value of x in ascending order
sort_axis = operator.itemgetter(0)
sorted_zip = sorted(zip(X_train,y_poly_pred), key=sort_axis)
X1, y1 = zip(*sorted_zip)

plt.plot(X1, y1, color = 'blue')
plt.xlabel('X')
plt.ylabel('Y')
plt.show()